# renovateã®ä»£ã‚ã‚Šã«package/actionã‚’æ›´æ–°ã™ã‚‹Dependabot

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "m2en"
    target-branch: main
    commit-message:
      prefix: chore
    labels:
      - "ğŸ”®dependabot update(npm)"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "m2en"
    target-branch: main
    commit-message:
      prefix: chore
    labels:
      - "ğŸ”®dependabot update(gh-actions)"
